module.exports = {
  ROLES: {
    SUPERADMIN: 'superadmin',
    ADMIN: 'admin'
  },
  
  YEARS: {
    FIRST: '1st Year',
    SECOND: '2nd Year',
    THIRD: '3rd Year',
    FOURTH: '4th Year'
  },

  ALLOWED_CONTRIBUTION_YEARS: ['2nd Year', '3rd Year', '4th Year'],
  RESTRICTED_CONTRIBUTION_YEARS: ['1st Year', '1st'],

  PAYMENT_METHODS: {
    CASH: 'Cash',
    UPI: 'UPI',
    BANK_TRANSFER: 'Bank Transfer'
  },

  CONTRIBUTION_STATUS: {
    PENDING: 'Pending',
    PARTIALLY_PAID: 'Partially Paid',
    PAID: 'Paid',
    NOT_ELIGIBLE: 'Not Eligible'
  },

  EXPENSE_CATEGORIES: [
    'Decoration',
    'Food',
    'Printing',
    'Gifts',
    'Flowers',
    'Hall',
    'Sound System',
    'Teacher Invitation',
    'Stationery',
    'Miscellaneous'
  ],

  EXPENSE_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected'
  },

  AUDIT_MODULES: {
    AUTH: 'AUTH',
    STUDENTS: 'STUDENTS',
    CONTRIBUTIONS: 'CONTRIBUTIONS',
    EXPENSES: 'EXPENSES',
    INVITATIONS: 'INVITATIONS',
    ADMINS: 'ADMINS',
    REPORTS: 'REPORTS',
    SYSTEM: 'SYSTEM'
  },

  AUDIT_ACTIONS: {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CREATE_ADMIN: 'CREATE_ADMIN',
    UPDATE_ADMIN: 'UPDATE_ADMIN',
    DISABLE_ADMIN: 'DISABLE_ADMIN',
    ENABLE_ADMIN: 'ENABLE_ADMIN',
    RESET_PASSWORD: 'RESET_PASSWORD',
    CREATE_STUDENT: 'CREATE_STUDENT',
    UPDATE_STUDENT: 'UPDATE_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
    CREATE_CONTRIBUTION: 'CREATE_CONTRIBUTION',
    EDIT_CONTRIBUTION: 'EDIT_CONTRIBUTION',
    DELETE_CONTRIBUTION: 'DELETE_CONTRIBUTION',
    REJECTED_CONTRIBUTION_FIRST_YEAR: 'REJECTED_CONTRIBUTION_FIRST_YEAR',
    CREATE_EXPENSE: 'CREATE_EXPENSE',
    UPDATE_EXPENSE: 'UPDATE_EXPENSE',
    APPROVE_EXPENSE: 'APPROVE_EXPENSE',
    REJECT_EXPENSE: 'REJECT_EXPENSE',
    DELETE_EXPENSE: 'DELETE_EXPENSE',
    CREATE_INVITATION: 'CREATE_INVITATION',
    UPDATE_INVITATION: 'UPDATE_INVITATION',
    DELETE_INVITATION: 'DELETE_INVITATION',
    EXPORT_REPORT: 'EXPORT_REPORT'
  },

  DEFAULT_PAGINATION_LIMIT: 20,
  MAX_PAGINATION_LIMIT: 100
};
